config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testeractions:
      branch: master
      repo: https://github.com/PalomoIFCA/testeractions
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-wheat-javanese.sh
        container: qc.acc_freaky-ochre-lizard
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testeractions find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-myrtle-guppy.sh
        container: qc.doc_seedy-amaranth-forest
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-wisteria-wasp.sh
        container: qc.doc_gamy-vermilion-snake
      github.com/PalomoIFCA/testeractions markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-beige-tamarin.sh
        container: qc.doc_lovely-cinnabar-gecko
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testeractions licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-russet-drever.sh
        container: qc.lic_muzzy-eggplant-liger
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testeractions bandit:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-dandelion-panda.sh
        container: qc.sec_sickly-green-havanese
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testeractions flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-taupe-seahorse.sh
        container: qc.sty_woozy-harlequin-skunk
      github.com/PalomoIFCA/testeractions jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-thistle-shrew.sh
        container: qc.sty_sickly-asparagus-hyena
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testeractions pytest:
        commands:
        - /usr/bin/env sh .sqa/script.beady-salmon-fish.sh
        container: qc.uni_silly-amethyst-boar
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testeractions get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-pumpkin-barracuda.sh
        container: qc.ver_woolly-olivine-dragon
timeout: 5400
