config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testeractions:
      branch: master
      repo: https://github.com/PalomoIFCA/testeractions
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-black-sparrow.sh
        container: qc.acc_hilly-grey-hummingbird
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testeractions find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-zucchini-bonobo.sh
        container: qc.doc_shaky-maroon-gharial
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-sapphire-terrier.sh
        container: qc.doc_stealthy-pumpkin-hornet
      github.com/PalomoIFCA/testeractions markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-brown-bird.sh
        container: qc.doc_snippy-turquoise-baboon
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testeractions licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-smalt-fowl.sh
        container: qc.lic_blurry-grey-caterpillar
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testeractions bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-razzmatazz-insect.sh
        container: qc.sec_homey-alizarin-kudu
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testeractions flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-grey-octopus.sh
        container: qc.sty_woolly-auburn-oyster
      github.com/PalomoIFCA/testeractions jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-teal-havanese.sh
        container: qc.sty_scanty-sepia-shark
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testeractions pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-wisteria-dugong.sh
        container: qc.uni_skanky-razzmatazz-oyster
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testeractions get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-razzmatazz-fly.sh
        container: qc.ver_stealthy-sepia-mongoose
timeout: 5400
