config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testeractions:
      branch: master
      repo: https://github.com/PalomoIFCA/testeractions
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-copper-dragon.sh
        container: qc.acc_fuzzy-seashell-husky
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testeractions find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-purple-oyster.sh
        container: qc.doc_surly-rust-raccoon
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-viridian-fly.sh
        container: qc.doc_nerdy-salmon-buzzard
      github.com/PalomoIFCA/testeractions markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-salmon-quoll.sh
        container: qc.doc_queasy-pumpkin-wrasse
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testeractions licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homely-wisteria-coral.sh
        container: qc.lic_hazy-sangria-tiger
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testeractions bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-red-tetra.sh
        container: qc.sec_hazy-ochre-eleuth
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testeractions flake8:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-copper-bonobo.sh
        container: qc.sty_freaky-turquoise-sparrow
      github.com/PalomoIFCA/testeractions jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-malachite-duck.sh
        container: qc.sty_bluesy-ivory-kakapo
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testeractions pytest:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-white-eel.sh
        container: qc.uni_scummy-champagne-monkey
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testeractions get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-zucchini-macaw.sh
        container: qc.ver_paltry-tan-gopher
timeout: 5400
