config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testeractions:
      branch: master
      repo: https://github.com/PalomoIFCA/testeractions
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-jade-elephant.sh
        container: qc.acc_squirrely-russet-dodo
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testeractions find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-zucchini-lion.sh
        container: qc.doc_homely-wisteria-warthog
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-turquoise-swan.sh
        container: qc.doc_trippy-pumpkin-chin
      github.com/PalomoIFCA/testeractions markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-aquamarine-drever.sh
        container: qc.doc_sloppy-cinnabar-caracal
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testeractions licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-sapphire-emu.sh
        container: qc.lic_tasty-pumpkin-llama
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testeractions bandit:
        commands:
        - /usr/bin/env sh .sqa/script.messy-myrtle-zebra.sh
        container: qc.sec_slaphappy-buff-gopher
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testeractions flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-lilac-eel.sh
        container: qc.sty_sunny-green-zebra
      github.com/PalomoIFCA/testeractions jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-xanthic-snail.sh
        container: qc.sty_bluesy-taupe-crab
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testeractions pytest:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-puce-macaque.sh
        container: qc.uni_woozy-cerise-wolf
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testeractions get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-beige-grouse.sh
        container: qc.ver_sleazy-zucchini-zebu
timeout: 5400
