config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testeractions:
      branch: master
      repo: https://github.com/PalomoIFCA/testeractions
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-bronze-clam.sh
        container: qc.acc_woolly-celadon-bordeaux
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testeractions find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-sapphire-zebra.sh
        container: qc.doc_homely-taupe-fox
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-black-yak.sh
        container: qc.doc_blurry-cardinal-husky
      github.com/PalomoIFCA/testeractions markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-auburn-giraffe.sh
        container: qc.doc_hazy-wheat-mammoth
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testeractions licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-puce-uguisu.sh
        container: qc.lic_cheeky-chocolate-binturong
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testeractions bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-azure-dodo.sh
        container: qc.sec_droopy-turquoise-wolfhound
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testeractions flake8:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-teal-chamois.sh
        container: qc.sty_wiggy-coral-baboon
      github.com/PalomoIFCA/testeractions jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-teal-lobster.sh
        container: qc.sty_slaphappy-brass-iguana
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testeractions pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-ultramarine-caterpillar.sh
        container: qc.uni_bumpy-lime-chamois
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testeractions get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-lilac-orangutan.sh
        container: qc.ver_snoopy-violet-slug
timeout: 5400
