config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testeractions:
      branch: master
      repo: https://github.com/PalomoIFCA/testeractions
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-chartreuse-seahorse.sh
        container: qc.acc_flabby-maroon-heron
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testeractions find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-firebrick-boar.sh
        container: qc.doc_droopy-malachite-mongoose
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-puce-zorse.sh
        container: qc.doc_hazy-sangria-newfoundland
      github.com/PalomoIFCA/testeractions markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-thistle-sheepdog.sh
        container: qc.doc_ugly-coral-spaniel
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testeractions licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-russet-tang.sh
        container: qc.lic_ugly-emerald-schnauzer
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testeractions bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-platinum-albatross.sh
        container: qc.sec_greasy-yellow-discus
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testeractions flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-orchid-booby.sh
        container: qc.sty_gamy-khaki-hummingbird
      github.com/PalomoIFCA/testeractions jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-black-skunk.sh
        container: qc.sty_squirrely-amaranth-tiger
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testeractions pytest:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-mustard-mayfly.sh
        container: qc.uni_trippy-chartreuse-bullfrog
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testeractions get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-brown-cat.sh
        container: qc.ver_silly-auburn-malamute
timeout: 5400
