config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testeractions:
      branch: master
      repo: https://github.com/PalomoIFCA/testeractions
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-ruby-terrier.sh
        container: qc.acc_surly-cerise-bloodhound
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testeractions find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-salmon-flounder.sh
        container: qc.doc_wimpy-cardinal-bongo
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-flax-lynx.sh
        container: qc.doc_paltry-brass-gibbon
      github.com/PalomoIFCA/testeractions markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-brown-wolf.sh
        container: qc.doc_ugly-tangerine-moorhen
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testeractions licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-burgundy-skunk.sh
        container: qc.lic_surly-magnolia-gar
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testeractions bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-fuchsia-cuttlefish.sh
        container: qc.sec_sunny-turquoise-elephant
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testeractions flake8:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-green-newt.sh
        container: qc.sty_sleepy-carmine-quail
      github.com/PalomoIFCA/testeractions jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-charcoal-uguisu.sh
        container: qc.sty_bumpy-cinnamon-horse
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testeractions pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-yellow-grouse.sh
        container: qc.uni_flabby-teal-havanese
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testeractions get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-wisteria-lemur.sh
        container: qc.ver_bluesy-vermilion-squid
timeout: 5400
