config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testeractions:
      branch: master
      repo: https://github.com/PalomoIFCA/testeractions
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-magnolia-shrew.sh
        container: qc.acc_scummy-heliotrope-cougar
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testeractions find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-buff-tapir.sh
        container: qc.doc_sunny-asparagus-harrier
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-brown-eagle.sh
        container: qc.doc_craggy-lilac-opossum
      github.com/PalomoIFCA/testeractions markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-indigo-tuatara.sh
        container: qc.doc_tasty-purple-snake
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testeractions licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-copper-zonkey.sh
        container: qc.lic_hazy-taupe-cow
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testeractions bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-tangerine-beaver.sh
        container: qc.sec_wiggy-puce-grasshopper
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testeractions flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-cerise-slug.sh
        container: qc.sty_cozy-ivory-gharial
      github.com/PalomoIFCA/testeractions jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-zucchini-chimpanzee.sh
        container: qc.sty_zippy-asparagus-chamois
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testeractions pytest:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-flax-chamois.sh
        container: qc.uni_slaphappy-emerald-lemur
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testeractions get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cyan-wolfhound.sh
        container: qc.ver_snazzy-chestnut-clam
timeout: 5400
