config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testeractions:
      branch: master
      repo: https://github.com/PalomoIFCA/testeractions
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-sangria-iguana.sh
        container: qc.acc_wiggy-chocolate-lion
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testeractions find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-lime-reindeer.sh
        container: qc.doc_seedy-chartreuse-abyssinian
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-amaranth-forest.sh
        container: qc.doc_muggy-peach-chin
      github.com/PalomoIFCA/testeractions markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-copper-beagle.sh
        container: qc.doc_cheeky-blue-civet
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testeractions licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-chocolate-paradise.sh
        container: qc.lic_ugly-azure-budgerigar
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testeractions bandit:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-puce-leopard.sh
        container: qc.sec_wheezy-saffron-tarantula
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testeractions flake8:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-orchid-frog.sh
        container: qc.sty_baggy-amethyst-vulture
      github.com/PalomoIFCA/testeractions jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-celadon-hummingbird.sh
        container: qc.sty_trippy-vermilion-saola
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testeractions pytest:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-periwinkle-monkey.sh
        container: qc.uni_sloppy-tangerine-opossum
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testeractions get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-indigo-russel.sh
        container: qc.ver_hazy-goldenrod-centipede
timeout: 5400
