config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testeractions:
      branch: master
      repo: https://github.com/PalomoIFCA/testeractions
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-yellow-swan.sh
        container: qc.acc_woozy-persimmon-ostrich
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testeractions find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-purple-bandicoot.sh
        container: qc.doc_freaky-dandelion-emu
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-purple-wolf.sh
        container: qc.doc_hasty-cornflower-wrasse
      github.com/PalomoIFCA/testeractions markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-aquamarine-jackal.sh
        container: qc.doc_foggy-magenta-giraffe
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testeractions licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-chocolate-starfish.sh
        container: qc.lic_snippy-cardinal-duck
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testeractions bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-mustard-zonkey.sh
        container: qc.sec_pasty-lime-mau
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testeractions flake8:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-olive-balinese.sh
        container: qc.sty_bumpy-violet-bison
      github.com/PalomoIFCA/testeractions jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-red-zonkey.sh
        container: qc.sty_baggy-lavender-collie
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testeractions pytest:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-maroon-stingray.sh
        container: qc.uni_pokey-bronze-mole
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testeractions get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-amber-mule.sh
        container: qc.ver_goopy-aquamarine-kakapo
timeout: 5400
