config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidiacwl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testeractions:
      branch: devel
      repo: https://github.com/PalomoIFCA/testeractions
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testeractions find_oph_workflows.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-aqua-wrasse.sh
        container: qc.sty_stuffy-goldenrod-beetle
timeout: 5400
