config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testeractions:
      branch: master
      repo: https://github.com/PalomoIFCA/testeractions
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-gold-seahorse.sh
        container: qc.acc_crappy-viridian-owl
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testeractions find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-ruby-liger.sh
        container: qc.doc_clammy-wheat-buzzard
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-white-albatross.sh
        container: qc.doc_ready-amber-newt
      github.com/PalomoIFCA/testeractions markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-cerise-squirrel.sh
        container: qc.doc_snappy-myrtle-moorhen
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testeractions licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-razzmatazz-neanderthal.sh
        container: qc.lic_skinny-charcoal-robin
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testeractions bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-magenta-ferret.sh
        container: qc.sec_gimpy-orange-meerkat
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testeractions flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-denim-greyhound.sh
        container: qc.sty_gamy-celadon-jaguar
      github.com/PalomoIFCA/testeractions jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-viridian-quoll.sh
        container: qc.sty_shaky-buff-woodlouse
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testeractions pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-rose-dalmatian.sh
        container: qc.uni_hasty-saffron-whale
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testeractions get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-alizarin-abyssinian.sh
        container: qc.ver_pretty-seashell-drever
timeout: 5400
