config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testeractions:
      branch: master
      repo: https://github.com/PalomoIFCA/testeractions
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-charcoal-shrew.sh
        container: qc.acc_leaky-celadon-caiman
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testeractions find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-eggplant-wasp.sh
        container: qc.doc_scaly-russet-cow
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-purple-rattlesnake.sh
        container: qc.doc_frumpy-maroon-goat
      github.com/PalomoIFCA/testeractions markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-brown-havanese.sh
        container: qc.doc_skanky-olive-barb
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testeractions licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-turquoise-rottweiler.sh
        container: qc.lic_dorky-ecru-turtle
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testeractions bandit:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-blue-husky.sh
        container: qc.sec_frumpy-thistle-raccoon
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testeractions flake8:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-wheat-mongrel.sh
        container: qc.sty_cozy-linen-shark
      github.com/PalomoIFCA/testeractions jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-maroon-hare.sh
        container: qc.sty_homely-ruby-dunker
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testeractions pytest:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-buff-quoll.sh
        container: qc.uni_sleepy-persimmon-dollar
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testeractions get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-auburn-paradise.sh
        container: qc.ver_gummy-pear-bracke
timeout: 5400
