config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testeractions:
      branch: master
      repo: https://github.com/PalomoIFCA/testeractions
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-salmon-wolfhound.sh
        container: qc.acc_droopy-blue-goat
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testeractions find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-pink-monster.sh
        container: qc.doc_seedy-carmine-saola
      github.com/PalomoIFCA/testeractions git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-burgundy-tortoise.sh
        container: qc.doc_shabby-yellow-chinchilla
      github.com/PalomoIFCA/testeractions markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-denim-cow.sh
        container: qc.doc_shabby-lemon-flamingo
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testeractions licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-wisteria-quetzal.sh
        container: qc.lic_sunny-heliotrope-woodlouse
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testeractions bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-brown-numbat.sh
        container: qc.sec_goopy-taupe-oriole
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testeractions flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-flax-squid.sh
        container: qc.sty_leaky-cyan-hyena
      github.com/PalomoIFCA/testeractions jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-chocolate-avocet.sh
        container: qc.sty_lumpy-aquamarine-chow
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testeractions pytest:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-lime-bongo.sh
        container: qc.uni_flaky-alizarin-salamander
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testeractions get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-copper-turkey.sh
        container: qc.ver_freaky-black-lion
timeout: 5400
